#!/usr/bin/env python3
"""Merge per-slide SRT files into one final SRT with correct time offsets.

Usage:
    py scripts/generate_subtitles.py <srt_dir> <audio_dir> <output.srt>

Reads srt_dir/slide-NN.srt (generated by synthesize_tts.py --srt) and
audio_dir/slide-NN.mp3 (for inter-slide timing). Merges all per-slide
SRTs into one file with accumulated time offsets.

Each per-slide SRT already has accurate word-level timing from Edge-TTS.
This script only adds the inter-slide time offset so all slides are
sequenced correctly in the final video.
"""

import argparse
import json
import os
import re
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from config import SLIDE_BUFFER_SECONDS


def get_audio_duration(mp3_path: Path) -> float:
    result = subprocess.run(
        ["ffprobe", "-v", "quiet", "-print_format", "json", "-show_format", str(mp3_path)],
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        return 3.0
    info = json.loads(result.stdout)
    return float(info.get("format", {}).get("duration", 3.0))


def split_into_lines(text: str, max_chars: int = 18) -> list[str]:
    """Split text into short subtitle lines at natural break points."""
    if len(text) <= max_chars:
        return [text]

    lines = []
    # Split at Chinese punctuation first
    parts = re.split(r"(?<=[。！？；，、])", text)
    current = ""
    for part in parts:
        if len(current + part) <= max_chars:
            current += part
        else:
            if current:
                lines.append(current.strip())
            # If single part is still too long, hard wrap
            while len(part) > max_chars:
                lines.append(part[:max_chars])
                part = part[max_chars:]
            current = part
    if current.strip():
        lines.append(current.strip())

    return lines if lines else [text]


def parse_srt_time(time_str: str) -> float:
    """Parse SRT time '00:01:23,456' to seconds."""
    match = re.match(r"(\d+):(\d+):(\d+)[,.](\d+)", time_str)
    if not match:
        return 0.0
    h, m, s, ms = match.groups()
    return int(h) * 3600 + int(m) * 60 + int(s) + int(ms) / 1000


def format_srt_time(seconds: float) -> str:
    h = int(seconds // 3600)
    m = int((seconds % 3600) // 60)
    s = int(seconds % 60)
    ms = int((seconds % 1) * 1000)
    return f"{h:02d}:{m:02d}:{s:02d},{ms:03d}"


def parse_srt_file(srt_path: Path) -> list[dict]:
    """Parse an SRT file into list of {start, end, text} entries."""
    content = srt_path.read_text(encoding="utf-8-sig").strip()
    if not content:
        return []

    entries = []
    blocks = re.split(r"\n\n+", content)
    for block in blocks:
        lines = block.strip().split("\n")
        if len(lines) < 3:
            continue
        time_match = re.match(r"(.+?)\s*-->\s*(.+)", lines[1])
        if not time_match:
            continue
        start = parse_srt_time(time_match.group(1).strip())
        end = parse_srt_time(time_match.group(2).strip())
        text = "\n".join(lines[2:])
        entries.append({"start": start, "end": end, "text": text})

    return entries


def main():
    parser = argparse.ArgumentParser(
        description="Merge per-slide SRTs into one final SRT with time offsets"
    )
    parser.add_argument("srt_dir", help="Directory with slide-NN.srt files")
    parser.add_argument("audio_dir", help="Directory with slide-NN.mp3 files (for inter-slide timing)")
    parser.add_argument("output", help="Output merged SRT file path")
    parser.add_argument("--max-chars", type=int, default=18, help="Max chars per subtitle line (default: 18)")
    args = parser.parse_args()

    srt_dir = Path(args.srt_dir)
    audio_dir = Path(args.audio_dir)
    output_path = Path(args.output)
    max_chars = args.max_chars

    if not srt_dir.exists():
        print(f"Error: SRT dir not found: {srt_dir}", file=sys.stderr)
        sys.exit(1)
    if not audio_dir.exists():
        print(f"Error: audio dir not found: {audio_dir}", file=sys.stderr)
        sys.exit(1)

    # Collect per-slide SRTs sorted by slide number
    srt_files = sorted(srt_dir.glob("slide-*.srt"))
    if not srt_files:
        print("Error: no slide-*.srt files found", file=sys.stderr)
        sys.exit(1)

    all_entries = []
    current_offset = 0.0
    buffer = SLIDE_BUFFER_SECONDS

    for srt_file in srt_files:
        slide_num = srt_file.stem.split(".")[0]  # slide-01
        mp3 = audio_dir / f"{slide_num}.mp3"
        audio_duration = get_audio_duration(mp3) if mp3.exists() else 3.0

        # Parse this slide's SRT entries
        entries = parse_srt_file(srt_file)

        # Add time offset + split long entries into ≤ max_chars chunks
        for entry in entries:
            text = entry["text"]
            entry_start = entry["start"] + current_offset
            entry_end = entry["end"] + current_offset
            entry_duration = entry_end - entry_start

            if len(text) <= max_chars:
                all_entries.append({"start": entry_start, "end": entry_end, "text": text})
            else:
                # Split long entry into short lines, distribute timing proportionally
                lines = split_into_lines(text, max_chars)
                total_chars = sum(len(l) for l in lines)
                t = entry_start
                for line in lines:
                    ratio = len(line) / total_chars if total_chars > 0 else 1 / len(lines)
                    line_dur = entry_duration * ratio
                    all_entries.append({"start": t, "end": t + line_dur, "text": line})
                    t += line_dur

        # Advance offset by audio duration + buffer
        current_offset += audio_duration + buffer

    # Write merged SRT
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        for i, entry in enumerate(all_entries, 1):
            f.write(f"{i}\n")
            f.write(f"{format_srt_time(entry['start'])} --> {format_srt_time(entry['end'])}\n")
            f.write(f"{entry['text']}\n\n")

    total_time = format_srt_time(current_offset)
    print(f"Done: {output_path} ({len(all_entries)} entries from {len(srt_files)} slides, {total_time} total)")


if __name__ == "__main__":
    main()
